kind: pipeline
name: default

steps:
- name: test
  image: node:9
  commands:
  - npm install -s -g recli
  - recli -h database -j 'r.db("rethinkdb").table("stats")'

services:
- name: database
  image: rethinkdb:2
  command: [ rethinkdb, --bind, all ]
  ports:
  - 28015
